name: "Infrastructure Security Scan"

on:
  pull_request:
    paths:
      - "terraform-app-infra/**"
      - "terraform-core-infra/**"
      - "terraform-state/**"

jobs:
  checkov-scan:
    name: "Checkov Static Analysis"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    strategy:
      matrix:
        directory: [terraform-app-infra, terraform-core-infra, terraform-state]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ matrix.directory }}

          soft_fail: true

          output_format: cli,sarif
          output_file_path: console,results_${{ matrix.directory }}.sarif

          framework: terraform

      - name: Upload SARIF results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: results_${{ matrix.directory }}.sarif
          category: checkov-${{ matrix.directory }}
