name: Check tfstate Network Rules
on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["Pull Request Infra", "Deploy SfSW Infra", "Destroy SfSW Infra"]
  #   types:
  #       - completed

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  check-tfstate-network-rules:
    environment: dev
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

    steps:

      - name: Azure CLI Login
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Check tfstate Network Rules
        uses: ./.github/actions/check-storage-network-rules
        with:
          storage-account-name: ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}
          resource-group-name: ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}     
    
      - name: Check Error Page Storage Network Rules
        uses: ./.github/actions/check-storage-network-rules
        with:
          storage-account-name: "sasfswxd01"
          resource-group-name: "s212d01-rg-sfswx-app"

