name: Deploy App Infra
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 7 * * 1-5'
  # push:
  #   branches:
  #     - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy-app-infra:
    if: github.event_name != 'pull_request'
    defaults:
      run:
        working-directory: terraform-app-infra
    environment: dev
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set TF_LOG to DEBUG
      #   run: echo "TF_LOG=DEBUG" >> $GITHUB_ENV

      - name: Read Config
        id: read_config
        uses: mikefarah/yq@master
        with:
          cmd: |
            echo "PROJECT_CODE=$(yq eval '.project_code' .github/config.yml)" >> $GITHUB_ENV
            echo "PROJECT_NAME=$(yq eval '.project_name' .github/config.yml)" >> $GITHUB_ENV
            echo "INSTANCE=$(yq eval '.instance' .github/config.yml)" >> $GITHUB_ENV

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.1"

      - name: Verify Terraform Installation
        run: |
          echo "PATH: $PATH"
          which terraform || echo "Terraform binary not found"
          terraform -version || echo "Terraform version check failed"

      - name: Echo GitHub Runner IP
        run: |
          GITHUB_RUNNER_IP=$(curl -s https://ifconfig.me)
          echo "GITHUB_RUNNER_IP=$GITHUB_RUNNER_IP" >> $GITHUB_ENV
          echo "GitHub Runner IP: $GITHUB_RUNNER_IP"

      - name: Azure CLI Login
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Enable Network Access for tfstate
        uses: ./.github/actions/manage-storage-network-access
        with:
          storage-account-name: ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}
          resource-group-name: ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}
          github-runner-ip: ${{ env.GITHUB_RUNNER_IP }}
          enable-network-access: true
          
      # replace hardcoded suffix when KV name is changed:
      - name: Enable Network Access for Key Vault
        uses: ./.github/actions/manage-keyvault-network-access
        with:
          keyvault-name: "kv-${{ env.PROJECT_NAME }}-${{ env.INSTANCE }}-temp-9"
          resource-group-name: "${{ env.PROJECT_CODE }}${{ env.INSTANCE }}-rg-${{ env.PROJECT_NAME }}-core-infra"
          github-runner-ip: ${{ env.GITHUB_RUNNER_IP }}
          enable-network-access: true

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}" \
            -backend-config="key=${{ secrets.APP_INFRA_STATE_KEY }}"

      - name: Terraform Plan
        id: plan
        run: terraform plan -var "resource_group_name=${{ env.PROJECT_CODE }}${{ env.INSTANCE }}-rg-${{ env.PROJECT_NAME }}-app"

      - name: Terraform Apply
        id: tf_apply
        run: |
          terraform apply -auto-approve -var "resource_group_name=${{ env.PROJECT_CODE }}${{ env.INSTANCE }}-rg-${{ env.PROJECT_NAME }}-app"
          echo "storage_account_name=$(terraform output -raw storage_account_name)" >> $GITHUB_OUTPUT
          echo "resource_group_name=$(terraform output -raw resource_group_name)" >> $GITHUB_OUTPUT
          echo "container_name=$(terraform output -raw container_name)" >> $GITHUB_OUTPUT
          
        # replace hardcoded suffix when KV name is changed:          
      - name: Disable Network Access for Key Vault
        uses: ./.github/actions/manage-keyvault-network-access
        with:
          keyvault-name: "kv-${{ env.PROJECT_NAME }}-${{ env.INSTANCE }}-temp-9"
          resource-group-name: "${{ env.PROJECT_CODE }}${{ env.INSTANCE }}-rg-${{ env.PROJECT_NAME }}-core-infra"
          github-runner-ip: ${{ env.GITHUB_RUNNER_IP }}
          enable-network-access: false

      - name: Set vnetImagePullEnabled for App Service
        uses: azure/CLI@v1
        with: 
          inlineScript: |          
            az resource update --resource-group "${{ env.PROJECT_CODE }}${{ env.INSTANCE }}-rg-${{ env.PROJECT_NAME }}-app" \
            --name "app-${{ env.PROJECT_NAME }}-${{ env.INSTANCE }}" --resource-type "Microsoft.Web/sites" \
            --set properties.vnetImagePullEnabled=true > /dev/null
            
      - name: Enable Network Access for Error Page Storage
        uses: ./.github/actions/manage-storage-network-access
        with:
          storage-account-name: ${{ steps.tf_apply.outputs.storage_account_name }}
          resource-group-name: ${{ steps.tf_apply.outputs.resource_group_name }}
          github-runner-ip: ${{ env.GITHUB_RUNNER_IP }}
          enable-network-access: true
          
      - name: Upload Error Pages
        run: |
          for file in ../error-pages/*.html; do
                filename=$(basename "$file")
                if [ "$(az storage blob exists \
                    --account-name ${{ steps.tf_apply.outputs.storage_account_name }} \
                    --container-name ${{ steps.tf_apply.outputs.container_name }} \
                    --name "$filename" \
                    --auth-mode login \
                    --query "exists" \
                    --output tsv)" = "false" ]; then
                  az storage blob upload \
                    --account-name ${{ steps.tf_apply.outputs.storage_account_name }} \
                    --container-name ${{ steps.tf_apply.outputs.container_name }} \
                    --file "$file" \
                    --name "$filename" \
                    --auth-mode login
                else
                  echo "Blob $filename already exists, skipping upload."
                fi
              done

      - name: Disable Network Access for tfstate 
        uses: ./.github/actions/manage-storage-network-access
        if: ${{ always() }}
        with:
          storage-account-name: ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}
          resource-group-name: ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}
          github-runner-ip: ${{ env.GITHUB_RUNNER_IP }}
          enable-network-access: false

      - name: Disable Network Access for Error Page Storage
        uses: ./.github/actions/manage-storage-network-access
        if: ${{ always() }}
        with:
          storage-account-name: ${{ steps.tf_apply.outputs.storage_account_name }}
          resource-group-name: ${{ steps.tf_apply.outputs.resource_group_name }}
          github-runner-ip: ${{ env.GITHUB_RUNNER_IP }}
          enable-network-access: false

      - name: Check Network Rules for tfstate 
        uses: ./.github/actions/check-storage-network-rules      
        if: ${{ always() }}
        id: network-rules        
        with:
          storage-account-name: ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}
          resource-group-name: ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}

      - name: Check Network Rules for Error Page Storage
        uses: ./.github/actions/check-storage-network-rules      
        if: ${{ always() }}
        id: network-rules-error-pages        
        with:
          storage-account-name: ${{ steps.tf_apply.outputs.storage_account_name }}
          resource-group-name: ${{ steps.tf_apply.outputs.resource_group_name }}
