name: Deploy App Infra
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy app infra:'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - pre-production
          - production
  schedule:
    - cron: '0 7 * * 1-5'
  # push:
  #   branches:
  #     - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

run-name: "Deploy app infra: ${{ inputs.environment || 'dev' }}"

jobs:
  deploy-app-infra:
    name: "Deploy app infra: ${{ inputs.environment || 'dev' }}"
    if: github.event_name != 'pull_request'
    defaults:
      run:
        working-directory: terraform-app-infra
    environment: "${{ inputs.environment || 'dev' }}" 
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ENV_NAME: ${{ inputs.environment || 'dev' }}
      APP_INFRA_RG_NAME: ${{ secrets.APP_INFRA_RG_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.1"

      - name: Verify Terraform Installation
        run: |
          echo "PATH: $PATH"
          which terraform || echo "Terraform binary not found"
          terraform -version || echo "Terraform version check failed"

      - name: Echo GitHub Runner IP
        run: |
          GITHUB_RUNNER_IP=$(curl -s https://ifconfig.me)
          echo "GITHUB_RUNNER_IP=$GITHUB_RUNNER_IP" >> $GITHUB_ENV
          echo "GitHub Runner IP: $GITHUB_RUNNER_IP"

      - name: Azure CLI Login
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Enable Network Access for tfstate
        uses: ./.github/actions/manage-storage-network-access
        with:
          storage-account-name: ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}
          resource-group-name: ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}
          github-runner-ip: ${{ env.GITHUB_RUNNER_IP }}
          enable-network-access: true
          
      - name: Enable Network Access for Key Vault
        uses: ./.github/actions/manage-keyvault-network-access
        with:
          keyvault-name: ${{ secrets.KEY_VAULT_NAME }}
          resource-group-name: ${{ secrets.CORE_INFRA_RG_NAME }}
          github-runner-ip: ${{ env.GITHUB_RUNNER_IP }}
          enable-network-access: true

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}" \
            -backend-config="key=${{ secrets.APP_INFRA_STATE_KEY }}"

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -var "resource_group_name=${APP_INFRA_RG_NAME}" \
            -var-file="terraform.${ENV_NAME}.tfvars"        

      - name: Terraform Apply
        id: tf_apply
        run: |
          terraform apply \
            -auto-approve -var "resource_group_name=${APP_INFRA_RG_NAME}" \
            -var-file="terraform.${ENV_NAME}.tfvars"
            echo "storage_account_name=$(terraform output -raw storage_account_name)" >> $GITHUB_OUTPUT
            echo "resource_group_name=$(terraform output -raw resource_group_name)" >> $GITHUB_OUTPUT
            echo "container_name=$(terraform output -raw container_name)" >> $GITHUB_OUTPUT

      - name: Disable Network Access for Key Vault
        uses: ./.github/actions/manage-keyvault-network-access
        if: ${{ always() }}
        with:
          keyvault-name: ${{ secrets.KEY_VAULT_NAME }}
          resource-group-name: ${{ secrets.CORE_INFRA_RG_NAME }}
          github-runner-ip: ${{ env.GITHUB_RUNNER_IP }}
          enable-network-access: false
            
      - name: Enable Network Access for Error Page Storage
        uses: ./.github/actions/manage-storage-network-access
        with:
          storage-account-name: ${{ steps.tf_apply.outputs.storage_account_name }}
          resource-group-name: ${{ steps.tf_apply.outputs.resource_group_name }}
          github-runner-ip: ${{ env.GITHUB_RUNNER_IP }}
          enable-network-access: true
          
      - name: Upload Error Pages
        run: |
          for file in ../error-pages/*.html; do
                filename=$(basename "$file")
                if [ "$(az storage blob exists \
                    --account-name ${{ steps.tf_apply.outputs.storage_account_name }} \
                    --container-name ${{ steps.tf_apply.outputs.container_name }} \
                    --name "$filename" \
                    --auth-mode login \
                    --query "exists" \
                    --output tsv)" = "false" ]; then
                  az storage blob upload \
                    --account-name ${{ steps.tf_apply.outputs.storage_account_name }} \
                    --container-name ${{ steps.tf_apply.outputs.container_name }} \
                    --file "$file" \
                    --name "$filename" \
                    --auth-mode login
                else
                  echo "Blob $filename already exists, skipping upload."
                fi
              done

      - name: Disable Network Access for tfstate 
        uses: ./.github/actions/manage-storage-network-access
        if: ${{ always() }}
        with:
          storage-account-name: ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}
          resource-group-name: ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}
          github-runner-ip: ${{ env.GITHUB_RUNNER_IP }}
          enable-network-access: false

      - name: Disable Network Access for Error Page Storage
        uses: ./.github/actions/manage-storage-network-access
        if: ${{ always() }}
        with:
          storage-account-name: ${{ steps.tf_apply.outputs.storage_account_name }}
          resource-group-name: ${{ secrets.APP_INFRA_RG_NAME }}
          github-runner-ip: ${{ env.GITHUB_RUNNER_IP }}
          enable-network-access: false

      - name: Check Network Rules for tfstate 
        uses: ./.github/actions/check-storage-network-rules      
        if: ${{ always() }}
        id: network-rules        
        with:
          storage-account-name: ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}
          resource-group-name: ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}

      - name: Check Network Rules for Error Page Storage
        uses: ./.github/actions/check-storage-network-rules      
        if: ${{ always() }}
        id: network-rules-error-pages        
        with:
          storage-account-name: ${{ steps.tf_apply.outputs.storage_account_name }}
          resource-group-name: ${{ secrets.APP_INFRA_RG_NAME }}
