name: deploy-sfsw-infra
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  quality-checks-and-pr:
    if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: terraform-app-infra
    name: Quality Checks
    environment: dev
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.1"

      - name: Echo GitHub Runner IP
        run: echo "GITHUB_RUNNER_IP=$(curl -s https://ifconfig.me)" >> $GITHUB_ENV

      - name: Azure CLI Login
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Fmt
        run: |
          terraform fmt -check || echo "Formatting issues detected:"
          terraform fmt -check -diff
        continue-on-error: true

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        id: checkov
        with:
          directory: .
          framework: terraform
          output_format: sarif
          output_file_path: results.sarif
          soft_fail: true

          # - name: Upload SARIF file
          #   uses: github/codeql-action/upload-sarif@v3
          #   with:
          #     sarif_file: results.sarif

      - name: Read SARIF Results
        id: sarif
        run: echo "CHECKOV_RESULT=$(cat results.sarif)" >> $GITHUB_ENV

      - name: Checkov Update Pull Request
        uses: actions/github-script@v7
        env:
          CHECKOV_RESULT: "${{ steps.checkov.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Checkov Scan üîç\`${{ steps.checkov.outcome }}\`
      
            <details><summary>Show Checkov Results</summary>
      
            \`\`\`\n
            ${process.env.CHECKOV_RESULT}
            \`\`\`
      
            </details>
      
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
      
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Run Trivy file scan
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0
        with:
          scan-type: "fs"
          scan-ref: "."
          ignore-unfixed: false
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH,MEDIUM,LOW"
          exit-code: 0
          vuln-type: os,library
          scanners: vuln,secret,misconfig,license

          # - name: Upload Trivy scan results to GitHub Security tab
          #   uses: github/codeql-action/upload-sarif@v3
          #   with:
          #     sarif_file: 'trivy-results.sarif'

      - name: Enable Storage Access
        run: |
          az storage account update \
            --resource-group ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }} \
            --name ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }} \
            --public-network-access Enabled \
            --default-action Deny

            az storage account network-rule add \
            --resource-group ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }} \
            --account-name ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }} \
            --ip-address $GITHUB_RUNNER_IP

      - name: Sleep for 30s
        run: |
          sleep 30

      - name: Verify Network Rule
        run: |
          az storage account show \
            --resource-group ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }} \
            --name ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }} \
            --query "{publicNetworkAccess:publicNetworkAccess, defaultAction:networkRuleSet.defaultAction}" \
            --output table

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}" \
            -backend-config="key=${{ secrets.BACKEND_AZURE_TF_STATE_KEY }}"

      - name: Terraform Validate
        run: terraform validate
        continue-on-error: true

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -var "resource_group_name=${{secrets.AZURE_RESOURCE_GROUP_NAME}}"
        continue-on-error: true

      - name: Disable Public Network Access
        run: |
          az storage account update \
            --resource-group ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }} \
            --name ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }} \
            --public-network-access Disabled

      - name: Remove Network Rule
        run: |
          az storage account network-rule remove \
            --resource-group ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }} \
            --account-name ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }} \
            --ip-address $GITHUB_RUNNER_IP

      - name: Update Pull Request
        uses: actions/github-script@v6
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Checkov Scan üîç\`${{ steps.checkov.outcome }}\`
            #### Terraform Plan üìñ\`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1





  deploy-to-dev:
    if: github.event_name != 'pull_request'
    defaults:
      run:
        working-directory: terraform-app-infra
    environment: dev
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      ARM_USE_AZUREAD: true
      ARM_USE_OIDC: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.1"

      - name: Verify Terraform Installation
        run: |
          echo "PATH: $PATH"
          which terraform || echo "Terraform binary not found"
          terraform -version || echo "Terraform version check failed"

      - name: Echo GitHub Runner IP
        run: echo "GITHUB_RUNNER_IP=$(curl -s https://ifconfig.me)" >> $GITHUB_ENV

      - name: Azure CLI Login
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Enable Storage Access
        run: |
          az storage account update \
            --resource-group ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }} \
            --name ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }} \
            --public-network-access Enabled \
            --default-action Deny

            az storage account network-rule add \
            --resource-group ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }} \
            --account-name ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }} \
            --ip-address $GITHUB_RUNNER_IP

      - name: Sleep for 30s
        run: |
          sleep 30

      - name: Verify Network Rule
        run: |
          az storage account show \
            --resource-group ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }} \
            --name ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }} \
            --query "{publicNetworkAccess:publicNetworkAccess, defaultAction:networkRuleSet.defaultAction}" \
            --output table

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}" \
            -backend-config="key=${{ secrets.BACKEND_AZURE_TF_STATE_KEY }}"

      - name: Terraform Plan
        id: plan
        run: terraform plan -var "resource_group_name=${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}"

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -var "resource_group_name=${{secrets.AZURE_RESOURCE_GROUP_NAME}}"

      - name: Disable Public Network Access
        run: |
          az storage account update \
            --resource-group ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }} \
            --name ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }} \
            --public-network-access Disabled

      - name: Remove Network Rule
        run: |
          az storage account network-rule remove \
            --resource-group ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }} \
            --account-name ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }} \
            --ip-address $GITHUB_RUNNER_IP
