name: Deploy SfSW Infra
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1-5'    
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy-to-dev:
    if: github.event_name != 'pull_request'
    defaults:
      run:
        working-directory: terraform-app-infra
    environment: dev
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.1"

      - name: Verify Terraform Installation
        run: |
          echo "PATH: $PATH"
          which terraform || echo "Terraform binary not found"
          terraform -version || echo "Terraform version check failed"

      - name: Echo GitHub Runner IP
        run: |
          GITHUB_RUNNER_IP=$(curl -s https://ifconfig.me)
          echo "GITHUB_RUNNER_IP=$GITHUB_RUNNER_IP" >> $GITHUB_ENV
          echo "GitHub Runner IP: $GITHUB_RUNNER_IP"

      - name: Azure CLI Login
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Enable tfstate Network Access
        uses: ./.github/actions/manage-tfstate-network-access
        with:
          backend-storage-account-name: ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}
          backend-resource-group-name: ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}
          github-runner-ip: ${{ env.GITHUB_RUNNER_IP }}
          enable-network-access: true

      - name: Sleep for 20s
        run: |
          sleep 20

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}" \
            -backend-config="key=${{ secrets.BACKEND_AZURE_TF_STATE_KEY }}"

      - name: Terraform Plan
        id: plan
        run: terraform plan -var "resource_group_name=${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}"

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -var "resource_group_name=${{secrets.AZURE_RESOURCE_GROUP_NAME}}"

      - name: Disable tfstate Network Access
        uses: ./.github/actions/manage-tfstate-network-access
        if: ${{ always() }}
        with:
          backend-storage-account-name: ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}
          backend-resource-group-name: ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}
          github-runner-ip: ${{ env.GITHUB_RUNNER_IP }}
          enable-network-access: false

      - name: Sleep for 20s
        run: |
          sleep 20
    
      - name: Check tfstate Network Rules
        uses: ./.github/actions/check-tfstate-network-rules      
        if: ${{ always() }}
        id: network-rules        
        with:
          backend-storage-account-name: ${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}
          backend-resource-group-name: ${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}
