name: Whitelist IP Address

on:
  workflow_dispatch:
    inputs:
      ip_address:
        description: 'User IP address to whitelist'
        required: true
      rule_name:
        description: 'Unique name for the NSG rule'
        required: true        
      environment:
        description: 'Whitelist IP Address:'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - pre-production


  # push:
  #   branches:
  #     - feature/*

permissions:
  id-token: write
  contents: read
  pull-requests: write

run-name: "Whitelist IP Address: ${{ inputs.environment }}"

jobs:
  whitelist-ip-address:
    name: "Whitelist IP Address: ${{ inputs.environment }}"
    if: github.event_name != 'pull_request'
    environment: "${{ inputs.environment }}" 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Add IP address to NSG inbound rules
        uses: ./.github/actions/whitelist-ip-address
        with:
          nsg-name-whitelist: ${{ secrets.NSG_NAME_WHITELIST }}
          infra-resource-group-name: ${{ secrets.INFRA_RESOURCE_GROUP_NAME }}
          rule-name: ${{ inputs.rule_name }}
          ip-address: ${{ inputs.ip_address }}

